$a::SendInput {:}regional_indicator_a{:}{Space}
$b::SendInput {:}regional_indicator_b{:}{Space}
$c::SendInput {:}regional_indicator_c{:}{Space}
$d::SendInput {:}regional_indicator_d{:}{Space}
$e::SendInput {:}regional_indicator_e{:}{Space}
$f::SendInput {:}regional_indicator_f{:}{Space}
$g::SendInput {:}regional_indicator_g{:}{Space}
$h::SendInput {:}regional_indicator_h{:}{Space}
$i::SendInput {:}regional_indicator_i{:}{Space}
$j::SendInput {:}regional_indicator_j{:}{Space}
$k::SendInput {:}regional_indicator_k{:}{Space}
$l::SendInput {:}regional_indicator_l{:}{Space}
$m::SendInput {:}regional_indicator_m{:}{Space}
$n::SendInput {:}regional_indicator_n{:}{Space}
$o::SendInput {:}regional_indicator_o{:}{Space}
$p::SendInput {:}regional_indicator_p{:}{Space}
$q::SendInput {:}regional_indicator_q{:}{Space}
$r::SendInput {:}regional_indicator_r{:}{Space}
$s::SendInput {:}regional_indicator_s{:}{Space}
$t::SendInput {:}regional_indicator_t{:}{Space}
$u::SendInput {:}regional_indicator_u{:}{Space}
$v::SendInput {:}regional_indicator_v{:}{Space}
$w::SendInput {:}regional_indicator_w{:}{Space}
$x::SendInput {:}regional_indicator_x{:}{Space}
$y::SendInput {:}regional_indicator_y{:}{Space}
$z::SendInput {:}regional_indicator_z{:}{Space}
$0::SendInput {:}zero{:}{Space}
$1::SendInput {:}one{:}{Space}
$2::SendInput {:}two{:}{Space}
$3::SendInput {:}three{:}{Space}
$4::SendInput {:}four{:}{Space}
$5::SendInput {:}five{:}{Space}
$6::SendInput {:}six{:}{Space}
$7::SendInput {:}seven{:}{Space}
$8::SendInput {:}eight{:}{Space}
$9::SendInput {:}nine{:}{Space}
$+a::SendInput {:}a{:}{Space}
$+b::SendInput {:}b{:}{Space}
$+o::SendInput {:}o2{:}{Space}