$a::SendInput {+}{:}regional_indicator_a{:}{Enter}
$b::SendInput {+}{:}regional_indicator_b{:}{Enter}
$c::SendInput {+}{:}regional_indicator_c{:}{Enter}
$d::SendInput {+}{:}regional_indicator_d{:}{Enter}
$e::SendInput {+}{:}regional_indicator_e{:}{Enter}
$f::SendInput {+}{:}regional_indicator_f{:}{Enter}
$g::SendInput {+}{:}regional_indicator_g{:}{Enter}
$h::SendInput {+}{:}regional_indicator_h{:}{Enter}
$i::SendInput {+}{:}regional_indicator_i{:}{Enter}
$j::SendInput {+}{:}regional_indicator_j{:}{Enter}
$k::SendInput {+}{:}regional_indicator_k{:}{Enter}
$l::SendInput {+}{:}regional_indicator_l{:}{Enter}
$m::SendInput {+}{:}regional_indicator_m{:}{Enter}
$n::SendInput {+}{:}regional_indicator_n{:}{Enter}
$o::SendInput {+}{:}regional_indicator_o{:}{Enter}
$p::SendInput {+}{:}regional_indicator_p{:}{Enter}
$q::SendInput {+}{:}regional_indicator_q{:}{Enter}
$r::SendInput {+}{:}regional_indicator_r{:}{Enter}
$s::SendInput {+}{:}regional_indicator_s{:}{Enter}
$t::SendInput {+}{:}regional_indicator_t{:}{Enter}
$u::SendInput {+}{:}regional_indicator_u{:}{Enter}
$v::SendInput {+}{:}regional_indicator_v{:}{Enter}
$w::SendInput {+}{:}regional_indicator_w{:}{Enter}
$x::SendInput {+}{:}regional_indicator_x{:}{Enter}
$y::SendInput {+}{:}regional_indicator_y{:}{Enter}
$z::SendInput {+}{:}regional_indicator_z{:}{Enter}
$0::SendInput {+}{:}zero{:}{Enter}
$1::SendInput {+}{:}one{:}{Enter}
$2::SendInput {+}{:}two{:}{Enter}
$3::SendInput {+}{:}three{:}{Enter}
$4::SendInput {+}{:}four{:}{Enter}
$5::SendInput {+}{:}five{:}{Enter}
$6::SendInput {+}{:}six{:}{Enter}
$7::SendInput {+}{:}seven{:}{Enter}
$8::SendInput {+}{:}eight{:}{Enter}
$9::SendInput {+}{:}nine{:}{Enter}
$+a::SendInput {+}{:}a{:}{Enter}
$+b::SendInput {+}{:}b{:}{Enter}
$+o::SendInput {+}{:}o2{:}{Enter}