$a::SendInput {+}{:}regional_indicator_a{:}{Space}{Enter}
$b::SendInput {+}{:}regional_indicator_b{:}{Space}{Enter}
$c::SendInput {+}{:}regional_indicator_c{:}{Space}{Enter}
$d::SendInput {+}{:}regional_indicator_d{:}{Space}{Enter}
$e::SendInput {+}{:}regional_indicator_e{:}{Space}{Enter}
$f::SendInput {+}{:}regional_indicator_f{:}{Space}{Enter}
$g::SendInput {+}{:}regional_indicator_g{:}{Space}{Enter}
$h::SendInput {+}{:}regional_indicator_h{:}{Space}{Enter}
$i::SendInput {+}{:}regional_indicator_i{:}{Space}{Enter}
$j::SendInput {+}{:}regional_indicator_j{:}{Space}{Enter}
$k::SendInput {+}{:}regional_indicator_k{:}{Space}{Enter}
$l::SendInput {+}{:}regional_indicator_l{:}{Space}{Enter}
$m::SendInput {+}{:}regional_indicator_m{:}{Space}{Enter}
$n::SendInput {+}{:}regional_indicator_n{:}{Space}{Enter}
$o::SendInput {+}{:}regional_indicator_o{:}{Space}{Enter}
$p::SendInput {+}{:}regional_indicator_p{:}{Space}{Enter}
$q::SendInput {+}{:}regional_indicator_q{:}{Space}{Enter}
$r::SendInput {+}{:}regional_indicator_r{:}{Space}{Enter}
$s::SendInput {+}{:}regional_indicator_s{:}{Space}{Enter}
$t::SendInput {+}{:}regional_indicator_t{:}{Space}{Enter}
$u::SendInput {+}{:}regional_indicator_u{:}{Space}{Enter}
$v::SendInput {+}{:}regional_indicator_v{:}{Space}{Enter}
$w::SendInput {+}{:}regional_indicator_w{:}{Space}{Enter}
$x::SendInput {+}{:}regional_indicator_x{:}{Space}{Enter}
$y::SendInput {+}{:}regional_indicator_y{:}{Space}{Enter}
$z::SendInput {+}{:}regional_indicator_z{:}{Space}{Enter}
$0::SendInput {+}{:}zero{:}{Space}{Enter}
$1::SendInput {+}{:}one{:}{Space}{Enter}
$2::SendInput {+}{:}two{:}{Space}{Enter}
$3::SendInput {+}{:}three{:}{Space}{Enter}
$4::SendInput {+}{:}four{:}{Space}{Enter}
$5::SendInput {+}{:}five{:}{Space}{Enter}
$6::SendInput {+}{:}six{:}{Space}{Enter}
$7::SendInput {+}{:}seven{:}{Space}{Enter}
$8::SendInput {+}{:}eight{:}{Space}{Enter}
$9::SendInput {+}{:}nine{:}{Space}{Enter}
$+a::SendInput {+}{:}a{:}{Space}{Enter}
$+b::SendInput {+}{:}b{:}{Space}{Enter}
$+o::SendInput {+}{:}o2{:}{Space}{Enter}