$a::SendInput {:}regional_indicator_a{:}
$b::SendInput {:}regional_indicator_b{:}
$c::SendInput {:}regional_indicator_c{:}
$d::SendInput {:}regional_indicator_d{:}
$e::SendInput {:}regional_indicator_e{:}
$f::SendInput {:}regional_indicator_f{:}
$g::SendInput {:}regional_indicator_g{:}
$h::SendInput {:}regional_indicator_h{:}
$i::SendInput {:}regional_indicator_i{:}
$j::SendInput {:}regional_indicator_j{:}
$k::SendInput {:}regional_indicator_k{:}
$l::SendInput {:}regional_indicator_l{:}
$m::SendInput {:}regional_indicator_m{:}
$n::SendInput {:}regional_indicator_n{:}
$o::SendInput {:}regional_indicator_o{:}
$p::SendInput {:}regional_indicator_p{:}
$q::SendInput {:}regional_indicator_q{:}
$r::SendInput {:}regional_indicator_r{:}
$s::SendInput {:}regional_indicator_s{:}
$t::SendInput {:}regional_indicator_t{:}
$u::SendInput {:}regional_indicator_u{:}
$v::SendInput {:}regional_indicator_v{:}
$w::SendInput {:}regional_indicator_w{:}
$x::SendInput {:}regional_indicator_x{:}
$y::SendInput {:}regional_indicator_y{:}
$z::SendInput {:}regional_indicator_z{:}
$0::SendInput {:}zero{:}
$1::SendInput {:}one{:}
$2::SendInput {:}two{:}
$3::SendInput {:}three{:}
$4::SendInput {:}four{:}
$5::SendInput {:}five{:}
$6::SendInput {:}six{:}
$7::SendInput {:}seven{:}
$8::SendInput {:}eight{:}
$9::SendInput {:}nine{:}
$+a::SendInput {:}a{:}
$+b::SendInput {:}b{:}
$+o::SendInput {:}o2{:}